name: TruffleHog Secret Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  trufflehog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install TruffleHog v3+
        run: pip install --upgrade trufflehog

      - name: Verify TruffleHog Version
        run: trufflehog --version  # Ensure it's v3+

      - name: Run TruffleHog (v3)
        run: trufflehog filesystem . --json --max_depth=50
